services:
  email_processor:
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ../..:/workspaces:cached
    working_dir: /workspaces/email_processor
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0 -p 3000"
    networks:
      - email_processor_network
    ports:
      - 3000:3000
    environment:
      RAILS_ENV: "development"
      DB_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
      - postgres

  postgres:
    image: postgres:16.1
    ports:
      - 5432:5432
    volumes:
      - email_processor_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - email_processor_network

  redis:
    image: redis:7.4
    ports:
      - "6379:6379"
    networks:
      - email_processor_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 2s

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    working_dir: /workspaces/email_processor
    command: bash -c "until redis-cli -h redis ping; do echo 'Esperando Redis...'; sleep 2; done; bundle exec sidekiq"
    networks:
      - email_processor_network
    environment:
      RAILS_ENV: "development"
      DB_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      REDIS_URL: redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_started

volumes:
  email_processor_postgres_data:

networks:
  email_processor_network:
    name: email_processor_network
