services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: YOH2mLwso7m
      POSTGRES_DB: database
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    image: pharmus_v2
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: f45a8b738106fa056ef7ec5adebca72e4ad37e8974503c06a0b7b540b3eddb7cb8077131392557279431bfbe6fdc86ee09c71235d7c6b56a20b87dee024d02c6
      DATABASE_URL: postgres://root:YOH2mLwso7m@db:5432/database
      REDIS_URL: redis://redis:6379/1
    volumes:
      - .:/rails
      - ./log:/rails/log
      - ./storage:/rails/storage
      - ./tmp:/rails/tmp
    depends_on:
      - db
      - redis
    restart: always
    command: bundle exec puma -C config/puma.rb

  sidekiq:
    build: .
    image: pharmus_v2
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://root:YOH2mLwso7m@db:5432/database
      REDIS_URL: redis://redis:6379/1
      SECRET_KEY_BASE: f45a8b738106fa056ef7ec5adebca72e4ad37e8974503c06a0b7b540b3eddb7cb8077131392557279431bfbe6fdc86ee09c71235d7c6b56a20b87dee024d02c6
    volumes:
      - ./log:/rails/log
    command: bundle exec sidekiq

volumes:
  pgdata:
