services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: YOH2mLwso7m
      POSTGRES_DB: database
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    image: pharmus_v2
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: aa7a5d...
      DATABASE_URL: postgres://root:YOH2mLwso7m@db:5432/database
    volumes:
      - ./log:/rails/log
      - ./storage:/rails/storage
    depends_on:
      - db
    restart: always

volumes:
  pgdata:
