development:
  adapter: redis
  url: redis://redis:6379/1
  channel_prefix: pharmus_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://192.168.0.202:6379/1" } %>
  channel_prefix: pharmus_production
