development:
  adapter: redis
  url: redis://redis:6379/0
  channel_prefix: email_processor_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://192.168.0.1:6379/1" } %>
  channel_prefix: email_processor_production
