default: &default
  adapter: postgresql
  encoding: unicode
  <% if ENV["DB_HOST"] %>
  host: <%= ENV["DB_HOST"] %>
  username: postgres
  password: postgres
  <% end %>

development:
  <<: *default
  database: pharmus_development

test:
  <<: *default
  database: pharmus_test

production:
  <<: *default
  database: pharmus_production
  username: root
  password: 'YOH2mLwso7m'
  host: db
