default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST", "postgres") %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgres") %>
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: email_processor_development

test:
  <<: *default
  database: email_processor_test

production:
  <<: *default
  database: email_processor_production
  username: root
  password: 'YOH2mLwso7m'
  host: db
